# ###########################################################
# +-------------------------------------------------------+ #
# |                 NatureCore (Messages)                 | #
# +-------------------------------------------------------+ #
# ###########################################################

welcome-message: "&8[&a+&8] &fWelcome to the server, %player%!"
quit-message: "&8[&c-&8] &f%player% left the server"
chat-message: "&f%player% &8| &r%message%"
chat-message-enable: true

# ###########################################################
# +-------------------------------------------------------+ #
# |                 NatureCore (Spawn)                    | #
# +-------------------------------------------------------+ #
# ###########################################################

spawn-on-join: false
spawn-coords: world,0,64,0,0,0

# ###########################################################
# +-------------------------------------------------------+ #
# |                 NatureCore (Whitelist)                | #
# +-------------------------------------------------------+ #
# ###########################################################

whitelist-enabled: false
whitelist: []
